// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCBS.Repositories.Models;

public partial class Schedule
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public DateTime WorkDate { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }
}