// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCBS.Repositories.Models;

public partial class ServiceCategory
{
    public Guid Id { get; set; }

    public Guid ServiceId { get; set; }

    public Guid CategoryId { get; set; }

    public string CategoryCode { get; set; }

    public string ImageUrl { get; set; }

    public int DisplayOrder { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Category Category { get; set; }

    public virtual Service Service { get; set; }
}